version: "3.9"
services:
  api:
    container_name: api
    build: ./api
    ports:
      - "8080:8080"
    tty: true # -tと同義。コンテナの標準入力を開く
    volumes:
      - ./api:/workspace:cached # chachedは同期の厳密性よりも速度を優先する
  web:
    container_name: web
    build: ./web
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api
